### ISSUE TITLE
[main/ERROR]: Entity gentlefawn:deer has no attributes

### ISSUE THREAD

**Issue by FewerFlaws** [FaeCraft/GentleFawn#3]
I get the following errors every time I start up.  The first entry may or may not be relevant, but the second clearly references GentleFawn.

[main/ERROR]: Write access detected to @Final field field_1705:Lnet/minecraft/class_329; in inventoryhotswap.mixins.json:HideHudMixin::handler$zlc000$onHudRender

[main/ERROR]: Entity gentlefawn:deer has no attributes

It's probably harmless by itself since the deer still spawn, wander around, etc.  But something isn't right.  Don't they deserve some attributes anyways?  They're very nice =P

**Comment by FewerFlaws** [comment]
This is on Minecraft 1.16.4, fabric version 0.6.1.51, gentlefawn version 1.1.2.

**Comment by gdude2002** [comment]
Hello, thanks for the report!

We've definitely seen `Entity gentlefawn:deer has no attributes` before — unfortunately, we have no idea what it actually is. Rest assured, however, that we are indeed giving the deer attributes — Minecraft just thinks they don't have any for some reason!

As for the first error you posted, that appears to be from a mod using the modid `inventoryhotswap`.

**Comment by FewerFlaws** [comment]
Thanks for getting back to me =]
