### ISSUE TITLE
Modpack inclusion

### ISSUE THREAD

**Issue by BrekiTomasson** [FaeCraft/GentleFawn#7]
I'm developing a modpack and would love to include GentleFawn. However, due to your license I have to ask your permission to rehost the distribution JAR in the downloadable bundle for the modpack? I would naturally link to your Curseforge and/or Github page and credit you for your work, would not take credit for anything other than bundling it in the modpack, and would not alter your work in any way. It would just mean including the JAR downloaded from Curseforge inside the ZIP for the modpack.

**Comment by gdude2002** [comment]
Hiya,

It's standard practice in the modding community at this point to have a license along those lines - it's very easy to find launchers that will download the mods from CurseForge at runtime, including launchers that are designed to be customized (like the skcraft launcher).

We do not plan on changing our license to accommodate people that wish to distribute our mods. Use a modpack format and launcher that downloads mods from CurseForge on behalf of the user instead.
